apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-g261
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-g261@sha256:ff1d018e434baf38e04e91bbfc739f2a4d0d69939209684e48ab3cba472c47b8
        name: my-nodejs
        resources: {}
status: {}
